INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('1', 'ASELSAN');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('2', 'ROKETSAN');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('3', 'TAI (Türk Havacılık ve Uzay Sanayii A.Ş.)');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('4', 'HAVELSAN');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('5', 'STM (Savunma Teknolojileri Mühendislik ve Ticaret A.Ş.)');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('6', 'MKEK (Makina ve Kimya Endüstrisi Kurumu)');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('7', 'FNSS');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('8', 'Otokar');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('9', 'BMC');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('10', 'Alp Havacılık');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('11', 'Kale Kalıp');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('12', 'Sarsılmaz');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('13', 'Nurol Makina');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('14', 'Katmerciler');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('15', 'TEI (TUSAŞ Motor Sanayii A.Ş.)');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('16', 'Meteksan Savunma');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('17', 'Ares Tersanesi');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('18', 'Yonca-Onuk Tersanesi');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('19', 'Dearsan Tersanesi');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('20', 'Havelsan Hava Elektronik Sanayi');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('21', 'Vestel Savunma');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('22', 'Baykar');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('23', 'FNSS Savunma Sistemleri');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('24', 'TÜMOSAN');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('25', 'MKE Ankaragücü');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('26', 'Canik TP9');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('27', 'Best Grup');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('28', 'Desan Tersanesi');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('29', 'Savronik');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('30', 'Aydın Yazılım ve Elektronik Sanayi');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('31', 'Arıkan Savunma');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('32', 'Ayesaş');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('33', 'Garanti Giyim Kompozit Teknolojileri');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('34', 'Hema Endüstri');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('35', 'KATMERCİLER');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('36', 'Karel Elektronik');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('37', 'Koc Holding');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('38', 'MilSOFT');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('39', 'Onur A.Ş.');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('40', 'Procend Defense');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('41', 'SDT Uzay ve Savunma Teknolojileri');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('42', 'Selex ES Elektronik');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('43', 'Simsoft');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('44', 'TAI TUSAŞ');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('45', 'THK Gökçen Aviation');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('46', 'TR Mekatronik');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('47', 'Turkish Aerospace Industries');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('48', 'UMTAS');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('49', 'Unidef');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('50', 'Vestel Defence');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('51', 'YAKUPOĞLU (YDS)');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('52', 'YDS Shoes');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('53', 'Yonca-Onuk JV');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('54', 'Anadolu Deniz İnşaat Kızakları');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('55', 'Aselsan MGEO');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('56', 'Aydın Yazılım');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('57', 'BİTES Savunma');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('58', 'BMC Power');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('59', 'Boğaziçi Savunma');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('60', 'Cesur Teknoloji');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('61', 'Dalaman Aircraft Factory');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('62', 'DelMar Defense');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('63', 'Ekin Teknoloji');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('64', 'ELSIS Elektronik Sistemler');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('65', 'Erko Elektronik');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('66', 'Girsan');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('67', 'Gölcük Shipyard');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('68', 'Hisar Savunma');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('69', 'Istanbul Denizcilik');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('70', 'Koç Savunma');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('71', 'KORKUT Systems');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('72', 'Kuzey Savunma');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('73', 'NATO Savunma');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('74', 'Nurol BAE Systems');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('75', 'Nurol Technology');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('76', 'ODTÜ TEKNOKENT');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('77', 'Öztek Savunma');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('78', 'PROFEN Communication Technologies');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('79', 'Profen Savunma');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('80', 'SanLab Simulation');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('81', 'STM Savunma');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('82', 'TAIS Shipyards');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('83', 'TUSAŞ Engine Industries');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('84', 'TAI Helicopter');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('85', 'Turksat Satellite Communication');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('86', 'TÜBİTAK SAGE');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('87', 'Türk Loydu');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('88', 'Üçel Savunma');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('89', 'ÜNTES Savunma');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('90', 'Vestel Elektronik');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('91', 'VİKO Savunma');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('92', 'Yenipazar Defense');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('93', 'Yıldız Teknopark');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('94', 'Yonca Onuk JV');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('95', 'ZSR Patlayıcı Sanayi');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('96', 'Zorlu Holding');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('97', 'Çukurova Savunma');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('98', 'Öztiryakiler');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('99', 'Barış Savunma');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('100', 'MTA Sismik');
