INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('1', 'Yonca-Onuk Tersanesi');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('2', 'Turksat Satellite Communication');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('3', 'Baykar');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('4', 'Ares Tersanesi');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('5', 'Karel Elektronik');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('6', 'TAI TUSAŞ');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('7', 'Üçel Savunma');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('8', 'Turkish Aerospace Industries');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('9', 'Arıkan Savunma');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('10', 'Öztiryakiler');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('11', 'THK Gökçen Aviation');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('12', 'Vestel Savunma');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('13', 'Ekin Teknoloji');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('14', 'ELSIS Elektronik Sistemler');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('15', 'Sarsılmaz');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('16', 'Baykar');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('17', 'Otokar');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('18', 'Ayesaş');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('19', 'Nurol Technology');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('20', 'Öztek Savunma');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('21', 'Üçel Savunma');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('22', 'ODTÜ TEKNOKENT');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('23', 'Hisar Savunma');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('24', 'Öztek Savunma');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('25', 'Havelsan Hava Elektronik Sanayi');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('26', 'Aselsan MGEO');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('27', 'MKEK (Makina ve Kimya Endüstrisi Kurumu)');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('28', 'NATO Savunma');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('29', 'Girsan');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('30', 'Çukurova Savunma');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('31', 'TAI TUSAŞ');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('32', 'ZSR Patlayıcı Sanayi');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('33', 'Arıkan Savunma');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('34', 'NATO Savunma');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('35', 'Cesur Teknoloji');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('36', 'ROKETSAN');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('37', 'Nurol Technology');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('38', 'Zorlu Holding');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('39', 'Koc Holding');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('40', 'Nurol Makina');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('41', 'Onur A.Ş.');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('42', 'Vestel Savunma');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('43', 'TR Mekatronik');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('44', 'Otokar');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('45', 'Ayesaş');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('46', 'Alp Havacılık');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('47', 'Öztiryakiler');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('48', 'Üçel Savunma');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('49', 'Dalaman Aircraft Factory');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('50', 'FNSS Savunma Sistemleri');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('51', 'PROFEN Communication Technologies');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('52', 'Desan Tersanesi');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('53', 'Kale Kalıp');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('54', 'Kale Kalıp');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('55', 'Onur A.Ş.');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('56', 'Aydın Yazılım ve Elektronik Sanayi');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('57', 'ODTÜ TEKNOKENT');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('58', 'MKEK (Makina ve Kimya Endüstrisi Kurumu)');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('59', 'Aydın Yazılım');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('60', 'ÜNTES Savunma');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('61', 'Erko Elektronik');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('62', 'Dalaman Aircraft Factory');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('63', 'Dearsan Tersanesi');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('64', 'ÜNTES Savunma');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('65', 'ROKETSAN');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('66', 'ÜNTES Savunma');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('67', 'Desan Tersanesi');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('68', 'Onur A.Ş.');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('69', 'Nurol Makina');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('70', 'Hisar Savunma');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('71', 'Hema Endüstri');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('72', 'Nurol Makina');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('73', 'Dalaman Aircraft Factory');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('74', 'BMC Power');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('75', 'Yıldız Teknopark');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('76', 'FNSS Savunma Sistemleri');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('77', 'MTA Sismik');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('78', 'Hisar Savunma');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('79', 'Otokar');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('80', 'Dearsan Tersanesi');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('81', 'Dearsan Tersanesi');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('82', 'Öztek Savunma');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('83', 'Nurol Makina');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('84', 'MKEK (Makina ve Kimya Endüstrisi Kurumu)');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('85', 'UMTAS');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('86', 'Istanbul Denizcilik');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('87', 'STM Savunma');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('88', 'STM (Savunma Teknolojileri Mühendislik ve Ticaret A.Ş.)');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('89', 'BMC Power');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('90', 'Yıldız Teknopark');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('91', 'STM (Savunma Teknolojileri Mühendislik ve Ticaret A.Ş.)');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('92', 'Hema Endüstri');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('93', 'Yonca-Onuk JV');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('94', 'PROFEN Communication Technologies');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('95', 'Turksat Satellite Communication');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('96', 'Arıkan Savunma');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('97', 'BMC');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('98', 'Havelsan Hava Elektronik Sanayi');
INSERT INTO `proje`.`tedarikçi` (`TedarikçiID`, `FirmaAdı`) VALUES ('99', 'BMC');
