INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('1', 'MKE 120mm Havan Topu', 'Silah', 'MKEK');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('2', 'ROKETSAN CİRİT Roketi', 'Mühimmat', 'ROKETSAN');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('3', 'ANKA İnsansız Hava Aracı', 'Hava Aracı', 'TAI');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('4', 'HAVELSAN Yazılımı', 'Yazılım', 'HAVELSAN');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('5', 'STM Kargı Mühimmatı', 'Mühimmat', 'STM');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('6', 'MKEK MG3 Makinalı Tüfek', 'Silah', 'MKEK');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('7', 'FNSS PARS 6x6', 'Kara Aracı', 'FNSS');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('8', 'Otokar Cobra', 'Kara Aracı', 'Otokar');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('9', 'BMC Kirpi', 'Kara Aracı', 'BMC');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('10', 'Alp Havacılık İHA', 'Hava Aracı', 'Alp Havacılık');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('11', 'Kale Kalıp SİHA', 'Hava Aracı', 'Kale Kalıp');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('12', 'Sarsılmaz Kılınç-2000', 'Silah', 'Sarsılmaz');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('13', 'Nurol Makina Ejder Yalçın', 'Kara Aracı', 'Nurol Makina');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('14', 'Katmerciler Hızır', 'Kara Aracı', 'Katmerciler');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('15', 'TEI TS1400 Turboşaft Motor', 'Hava Aracı', 'TEI');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('16', 'Meteksan Savunma Akıllı Mühimmat', 'Mühimmat', 'Meteksan');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('17', 'Ares Tersanesi Korvet', 'Deniz Aracı', 'Ares Tersanesi');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('18', 'Yonca-Onuk Tersanesi Zırhlı Bot', 'Deniz Aracı', 'Yonca-Onuk');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('19', 'Dearsan Tersanesi Fırkateyn', 'Deniz Aracı', 'Dearsan');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('20', 'Vestel Elektronik Savaş Sistemi', 'Elektronik', 'Vestel');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('21', 'Baykar Bayraktar TB2', 'Hava Aracı', 'Baykar');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('22', 'Desan Tersanesi Yat', 'Deniz Aracı', 'Desan');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('23', 'Savronik Elektronik Mühimmat', 'Mühimmat', 'Savronik');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('24', 'Aydın Elektronik Sistemler', 'Yazılım', 'Aydın');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('25', 'Arıkan Savunma Zırhlı Araç', 'Kara Aracı', 'Arıkan Savunma');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('26', 'Ayesaş Elektronik Cihaz', 'Elektronik', 'Ayesaş');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('27', 'Garanti Kompozit Teknolojileri', 'Kompozit', 'Garanti Giyim');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('28', 'Hema Endüstri Mühimmat', 'Mühimmat', 'Hema');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('29', 'KATMERCİLER Zırhlı Araç', 'Kara Aracı', 'KATMERCİLER');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('30', 'Karel Elektronik Savunma', 'Elektronik', 'Karel');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('31', 'MilSOFT Yazılım Sistemi', 'Yazılım', 'MilSOFT');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('32', 'Onur A.Ş. Savunma Teknolojileri', 'Teknoloji', 'Onur A.Ş.');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('33', 'Procend Defense Sistemleri', 'Savunma', 'Procend');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('34', 'SDT  Savunma Teknolojileri', 'Hava Aracı', 'SDT');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('35', 'Selex ES Elektronik Sistemi', 'Elektronik', 'Selex ES');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('36', 'Simsoft Simülasyon Sistemi', 'Simülasyon', 'Simsoft');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('37', 'TAI T129 ATAK Helikopteri', 'Hava Aracı', 'TAI');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('38', 'THK Gökçen Uçakları', 'Hava Aracı', 'THK');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('39', 'TR Mekatronik Sistemler', 'Mekatronik', 'TR Mekatronik');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('40', 'Türk Loydu Sertifikasyon', 'Sertifikasyon', 'Türk Loydu');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('41', 'Üçel Savunma Zırhlı Araç', 'Kara Aracı', 'Üçel Savunma');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('42', 'ÜNTES Savunma Elektroniği', 'Elektronik', 'ÜNTES');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('43', 'Vestel Elektronik Savunma', 'Elektronik', 'Vestel');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('44', 'VİKO Savunma Ürünleri', 'Elektronik', 'VİKO');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('45', 'Yenipazar Defense', 'Savunma', 'Yenipazar');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('46', 'Yıldız Teknopark Teknoloji', 'Teknoloji', 'Yıldız Teknopark');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('47', 'Yonca-Onuk JV Zırhlı Araç', 'Kara Aracı', 'Yonca-Onuk');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('48', 'ZSR Patlayıcı Sanayi', 'Patlayıcı', 'ZSR');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('49', 'Çukurova Savunma Sistemleri', 'Savunma', 'Çukurova');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('50', 'Öztiryakiler Savunma Ekipmanları', 'Ekipman', 'Öztiryakiler');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('51', 'Barış Savunma Zırhlı Araç', 'Kara Aracı', 'Barış Savunma');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('52', 'MTA Sismik Araçlar', 'Sismik', 'MTA');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('53', 'Aselsan 3D Radar Sistemi', 'Radar', 'Aselsan');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('54', 'ROKETSAN Atmaca Füzesi', 'Füze', 'ROKETSAN');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('55', 'TAI HÜRJET', 'Hava Aracı', 'TAI');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('56', 'HAVELSAN Savunma Simülatörü', 'Simülatör', 'HAVELSAN');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('57', 'STM Akya Denizaltı Torpidosu', 'Torpido', 'STM');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('58', 'MKEK Yavuz Tüfeği', 'Silah', 'MKEK');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('59', 'FNSS Kaplan', 'Kara Aracı', 'FNSS');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('60', 'Otokar Arma', 'Kara Aracı', 'Otokar');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('61', 'BMC Vuran', 'Kara Aracı', 'BMC');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('62', 'Alp Havacılık Hava İHA', 'Hava Aracı', 'Alp Havacılık');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('63', 'Kale Kalıp SİHA', 'Hava Aracı', 'Kale Kalıp');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('64', 'Sarsılmaz Canik', 'Silah', 'Sarsılmaz');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('65', 'Nurol Makina BMC', 'Kara Aracı', 'Nurol Makina');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('66', 'Katmerciler KAPLAN', 'Kara Aracı', 'Katmerciler');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('67', 'TEI TS1400 Motor', 'Hava Aracı', 'TEI');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('68', 'Meteksan Savunma Mühimmat', 'Mühimmat', 'Meteksan');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('69', 'Ares Tersanesi Karakol Botu', 'Deniz Aracı', 'Ares Tersanesi');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('70', 'Yonca-Onuk Tersanesi Hız Botu', 'Deniz Aracı', 'Yonca-Onuk');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('71', 'Dearsan Tersanesi Yat', 'Deniz Aracı', 'Dearsan');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('72', 'Vestel Savunma Elektroniği', 'Elektronik', 'Vestel');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('73', 'Baykar Bayraktar Akinci', 'Hava Aracı', 'Baykar');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('74', 'Desan Tersanesi Güç Botu', 'Deniz Aracı', 'Desan');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('75', 'Savronik Elektronik Mühimmat', 'Mühimmat', 'Savronik');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('76', 'Aydın Yazılım Savunma', 'Yazılım', 'Aydın');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('77', 'Arıkan Savunma Zırhlı Araç', 'Kara Aracı', 'Arıkan Savunma');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('78', 'Ayesaş Elektronik Savunma', 'Elektronik', 'Ayesaş');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('79', 'Garanti Giyim Savunma', 'Kompozit', 'Garanti Giyim');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('80', 'Hema Endüstri Savunma', 'Mühimmat', 'Hema');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('81', 'KATMERCİLER Savunma Aracı', 'Kara Aracı', 'KATMERCİLER');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('82', 'Karel Elektronik Savunma', 'Elektronik', 'Karel');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('83', 'MilSOFT Savunma', 'Yazılım', 'MilSOFT');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('84', 'Onur Savunma Teknolojileri', 'Teknoloji', 'Onur A.Ş.');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('85', 'Procend Defense Savunma', 'Savunma', 'Procend');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('86', 'SDT Uzay Savunma', 'Hava Aracı', 'SDT');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('87', 'Selex ES Elektronik', 'Elektronik', 'Selex ES');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('88', 'Simsoft Savunma', 'Simülasyon', 'Simsoft');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('89', 'TAI Hürjet', 'Hava Aracı', 'TAI');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('90', 'THK Gökçen', 'Hava Aracı', 'THK');
INSERT INTO `proje`.`materyal` (`MateryalID`, `MateryalAdı`, `Tür`, `Marka`) VALUES ('91', 'TR Mekatronik Savunma', 'Mekatronik', 'TR Mekatronik');
